language: swift

osx_image: xcode10.1
env:
  matrix:
    - TEST_SDK=iphonesimulator10 OS=10 NAME='iPhone XR'
    - TEST_SDK=iphonesimulator10 OS=10 NAME='iPhone 7'

script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project GenUtilsLib.xcodeproj -scheme GenUtilsLib -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES
